const PANTRY_TEMPLATES = {
  indian: {
    name: 'Indian / South Asian',
    icon: '🍛',
    description: 'Essential spices, lentils, and staples for Indian cooking',
    items: [
      { name: 'Basmati Rice', quantity: 2, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Whole Wheat Flour (Atta)', quantity: 5, unit: 'kg', category: 'Dry goods', icon: '🌾' },
      { name: 'Yellow Lentils (Moong Dal)', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Red Lentils (Masoor Dal)', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Chickpeas (Chana)', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Cumin Seeds', quantity: 100, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Coriander Powder', quantity: 100, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Turmeric Powder', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Red Chili Powder', quantity: 100, unit: 'g', category: 'Spices', icon: '🌶️' },
      { name: 'Garam Masala', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Mustard Seeds', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Ghee', quantity: 500, unit: 'g', category: 'Fridge', icon: '🧈' },
      { name: 'Cooking Oil', quantity: 1, unit: 'L', category: 'Dry goods', icon: '🫙' },
      { name: 'Onions', quantity: 2, unit: 'kg', category: 'Produce', icon: '🧅' },
      { name: 'Garlic', quantity: 200, unit: 'g', category: 'Produce', icon: '🧄' },
      { name: 'Ginger', quantity: 200, unit: 'g', category: 'Produce', icon: '🫚' },
      { name: 'Tomatoes', quantity: 1, unit: 'kg', category: 'Produce', icon: '🍅' },
      { name: 'Yogurt', quantity: 500, unit: 'g', category: 'Fridge', icon: '🥛' },
      { name: 'Tea (Chai)', quantity: 250, unit: 'g', category: 'Dry goods', icon: '🍵' },
      { name: 'Salt', quantity: 500, unit: 'g', category: 'Spices', icon: '🧂' },
    ]
  },
  mediterranean: {
    name: 'Mediterranean',
    icon: '🫒',
    description: 'Olive oil, legumes, and herbs for Mediterranean cuisine',
    items: [
      { name: 'Olive Oil', quantity: 1, unit: 'L', category: 'Dry goods', icon: '🫒' },
      { name: 'Pasta', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🍝' },
      { name: 'Canned Tomatoes', quantity: 4, unit: 'pcs', category: 'Dry goods', icon: '🥫' },
      { name: 'Chickpeas', quantity: 500, unit: 'g', category: 'Dry goods', icon: '🫘' },
      { name: 'Lentils', quantity: 500, unit: 'g', category: 'Dry goods', icon: '🫘' },
      { name: 'Feta Cheese', quantity: 200, unit: 'g', category: 'Fridge', icon: '🧀' },
      { name: 'Kalamata Olives', quantity: 200, unit: 'g', category: 'Fridge', icon: '🫒' },
      { name: 'Garlic', quantity: 200, unit: 'g', category: 'Produce', icon: '🧄' },
      { name: 'Lemons', quantity: 4, unit: 'pcs', category: 'Produce', icon: '🍋' },
      { name: 'Oregano', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Basil', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Rosemary', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Rice', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Quinoa', quantity: 500, unit: 'g', category: 'Dry goods', icon: '🌾' },
      { name: 'Greek Yogurt', quantity: 500, unit: 'g', category: 'Fridge', icon: '🥛' },
      { name: 'Tahini', quantity: 300, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Honey', quantity: 300, unit: 'g', category: 'Dry goods', icon: '🍯' },
      { name: 'Walnuts', quantity: 200, unit: 'g', category: 'Snacks', icon: '🫘' },
    ]
  },
  mexican: {
    name: 'Mexican / Latin American',
    icon: '🌮',
    description: 'Beans, spices, and staples for Mexican cooking',
    items: [
      { name: 'Black Beans', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Pinto Beans', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'White Rice', quantity: 2, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Corn Tortillas', quantity: 12, unit: 'pcs', category: 'Dry goods', icon: '🫓' },
      { name: 'Cumin', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Chili Powder', quantity: 50, unit: 'g', category: 'Spices', icon: '🌶️' },
      { name: 'Smoked Paprika', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Oregano', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Garlic Powder', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Canned Tomatoes', quantity: 4, unit: 'pcs', category: 'Dry goods', icon: '🥫' },
      { name: 'Salsa', quantity: 2, unit: 'pcs', category: 'Condiments', icon: '🫙' },
      { name: 'Lime', quantity: 4, unit: 'pcs', category: 'Produce', icon: '🍋' },
      { name: 'Onions', quantity: 1, unit: 'kg', category: 'Produce', icon: '🧅' },
      { name: 'Garlic', quantity: 200, unit: 'g', category: 'Produce', icon: '🧄' },
      { name: 'Jalapeños', quantity: 4, unit: 'pcs', category: 'Produce', icon: '🌶️' },
      { name: 'Cheddar Cheese', quantity: 200, unit: 'g', category: 'Fridge', icon: '🧀' },
      { name: 'Sour Cream', quantity: 200, unit: 'g', category: 'Fridge', icon: '🥛' },
      { name: 'Cooking Oil', quantity: 1, unit: 'L', category: 'Dry goods', icon: '🫙' },
    ]
  },
  chinese: {
    name: 'Chinese / East Asian',
    icon: '🥢',
    description: 'Sauces, noodles, and essentials for Chinese cooking',
    items: [
      { name: 'Jasmine Rice', quantity: 2, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Noodles', quantity: 500, unit: 'g', category: 'Dry goods', icon: '🍜' },
      { name: 'Soy Sauce', quantity: 500, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Oyster Sauce', quantity: 300, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Sesame Oil', quantity: 200, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Rice Vinegar', quantity: 300, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Hoisin Sauce', quantity: 200, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Cornstarch', quantity: 200, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Ginger', quantity: 200, unit: 'g', category: 'Produce', icon: '🫚' },
      { name: 'Garlic', quantity: 200, unit: 'g', category: 'Produce', icon: '🧄' },
      { name: 'Spring Onions', quantity: 200, unit: 'g', category: 'Produce', icon: '🌿' },
      { name: 'Tofu', quantity: 400, unit: 'g', category: 'Fridge', icon: '🧊' },
      { name: 'Cooking Oil', quantity: 1, unit: 'L', category: 'Dry goods', icon: '🫙' },
      { name: 'Five Spice Powder', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Dried Chili Flakes', quantity: 50, unit: 'g', category: 'Spices', icon: '🌶️' },
      { name: 'Shaoxing Wine', quantity: 200, unit: 'ml', category: 'Condiments', icon: '🫙' },
    ]
  },
  japanese: {
    name: 'Japanese',
    icon: '🍱',
    description: 'Miso, dashi, and essentials for Japanese cooking',
    items: [
      { name: 'Japanese Short Grain Rice', quantity: 2, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Miso Paste', quantity: 300, unit: 'g', category: 'Fridge', icon: '🫙' },
      { name: 'Soy Sauce', quantity: 500, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Mirin', quantity: 300, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Rice Vinegar', quantity: 200, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Sesame Oil', quantity: 200, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Dashi Stock', quantity: 4, unit: 'pcs', category: 'Dry goods', icon: '🫙' },
      { name: 'Nori Sheets', quantity: 10, unit: 'pcs', category: 'Dry goods', icon: '🌿' },
      { name: 'Panko Breadcrumbs', quantity: 200, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Tofu', quantity: 400, unit: 'g', category: 'Fridge', icon: '🧊' },
      { name: 'Edamame', quantity: 300, unit: 'g', category: 'Freezer', icon: '🫘' },
      { name: 'Ginger', quantity: 100, unit: 'g', category: 'Produce', icon: '🫚' },
      { name: 'Spring Onions', quantity: 100, unit: 'g', category: 'Produce', icon: '🌿' },
      { name: 'Sesame Seeds', quantity: 100, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Wasabi Paste', quantity: 50, unit: 'g', category: 'Condiments', icon: '🫙' },
    ]
  },
  middleeastern: {
    name: 'Middle Eastern',
    icon: '🧆',
    description: 'Spices, legumes, and staples for Middle Eastern cooking',
    items: [
      { name: 'Basmati Rice', quantity: 2, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Chickpeas', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Lentils', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Tahini', quantity: 300, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Olive Oil', quantity: 1, unit: 'L', category: 'Dry goods', icon: '🫒' },
      { name: 'Cumin', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Coriander', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Cinnamon', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Cardamom', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Sumac', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Za\'atar', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Flatbread (Pita)', quantity: 6, unit: 'pcs', category: 'Dry goods', icon: '🫓' },
      { name: 'Garlic', quantity: 200, unit: 'g', category: 'Produce', icon: '🧄' },
      { name: 'Lemons', quantity: 4, unit: 'pcs', category: 'Produce', icon: '🍋' },
      { name: 'Onions', quantity: 1, unit: 'kg', category: 'Produce', icon: '🧅' },
      { name: 'Pomegranate Molasses', quantity: 200, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Rose Water', quantity: 100, unit: 'ml', category: 'Condiments', icon: '🫙' },
    ]
  },
  canadian: {
    name: 'Canadian / Western',
    icon: '🍁',
    description: 'Everyday staples for Canadian and Western cooking',
    items: [
      { name: 'All Purpose Flour', quantity: 2, unit: 'kg', category: 'Dry goods', icon: '🌾' },
      { name: 'White Rice', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Pasta', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🍝' },
      { name: 'Oats', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🌾' },
      { name: 'Canned Beans', quantity: 4, unit: 'pcs', category: 'Dry goods', icon: '🥫' },
      { name: 'Canned Tomatoes', quantity: 4, unit: 'pcs', category: 'Dry goods', icon: '🥫' },
      { name: 'Chicken Broth', quantity: 2, unit: 'pcs', category: 'Dry goods', icon: '🥫' },
      { name: 'Olive Oil', quantity: 500, unit: 'ml', category: 'Dry goods', icon: '🫒' },
      { name: 'Butter', quantity: 250, unit: 'g', category: 'Fridge', icon: '🧈' },
      { name: 'Eggs', quantity: 12, unit: 'pcs', category: 'Fridge', icon: '🥚' },
      { name: 'Milk', quantity: 2, unit: 'L', category: 'Fridge', icon: '🥛' },
      { name: 'Cheddar Cheese', quantity: 400, unit: 'g', category: 'Fridge', icon: '🧀' },
      { name: 'Garlic', quantity: 100, unit: 'g', category: 'Produce', icon: '🧄' },
      { name: 'Onions', quantity: 1, unit: 'kg', category: 'Produce', icon: '🧅' },
      { name: 'Potatoes', quantity: 2, unit: 'kg', category: 'Produce', icon: '🥔' },
      { name: 'Salt', quantity: 500, unit: 'g', category: 'Spices', icon: '🧂' },
      { name: 'Black Pepper', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Maple Syrup', quantity: 250, unit: 'ml', category: 'Condiments', icon: '🍯' },
    ]
  },
  vegan: {
    name: 'Vegan / Plant Based',
    icon: '🌱',
    description: 'Plant-based proteins, grains, and essentials',
    items: [
      { name: 'Quinoa', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🌾' },
      { name: 'Brown Rice', quantity: 2, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Lentils', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Chickpeas', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Black Beans', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Tofu', quantity: 400, unit: 'g', category: 'Fridge', icon: '🧊' },
      { name: 'Tempeh', quantity: 300, unit: 'g', category: 'Fridge', icon: '🧊' },
      { name: 'Oat Milk', quantity: 2, unit: 'L', category: 'Fridge', icon: '🥛' },
      { name: 'Nutritional Yeast', quantity: 200, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Tahini', quantity: 300, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Olive Oil', quantity: 1, unit: 'L', category: 'Dry goods', icon: '🫒' },
      { name: 'Nuts Mix', quantity: 500, unit: 'g', category: 'Snacks', icon: '🫘' },
      { name: 'Seeds Mix', quantity: 200, unit: 'g', category: 'Dry goods', icon: '🌿' },
      { name: 'Coconut Milk', quantity: 4, unit: 'pcs', category: 'Dry goods', icon: '🥥' },
      { name: 'Soy Sauce', quantity: 300, unit: 'ml', category: 'Condiments', icon: '🫙' },
      { name: 'Maple Syrup', quantity: 250, unit: 'ml', category: 'Condiments', icon: '🍯' },
      { name: 'Apple Cider Vinegar', quantity: 300, unit: 'ml', category: 'Condiments', icon: '🫙' },
    ]
  },
  keto: {
    name: 'Keto / Low Carb',
    icon: '🥩',
    description: 'High fat, low carb essentials for keto diet',
    items: [
      { name: 'Almond Flour', quantity: 500, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Coconut Flour', quantity: 500, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Eggs', quantity: 12, unit: 'pcs', category: 'Fridge', icon: '🥚' },
      { name: 'Butter', quantity: 500, unit: 'g', category: 'Fridge', icon: '🧈' },
      { name: 'Heavy Cream', quantity: 500, unit: 'ml', category: 'Fridge', icon: '🥛' },
      { name: 'Cream Cheese', quantity: 250, unit: 'g', category: 'Fridge', icon: '🧀' },
      { name: 'Cheddar Cheese', quantity: 400, unit: 'g', category: 'Fridge', icon: '🧀' },
      { name: 'Bacon', quantity: 500, unit: 'g', category: 'Fridge', icon: '🥓' },
      { name: 'Olive Oil', quantity: 1, unit: 'L', category: 'Dry goods', icon: '🫒' },
      { name: 'Coconut Oil', quantity: 500, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Avocados', quantity: 4, unit: 'pcs', category: 'Produce', icon: '🥑' },
      { name: 'Almonds', quantity: 500, unit: 'g', category: 'Snacks', icon: '🫘' },
      { name: 'Walnuts', quantity: 300, unit: 'g', category: 'Snacks', icon: '🫘' },
      { name: 'Chia Seeds', quantity: 200, unit: 'g', category: 'Dry goods', icon: '🌿' },
      { name: 'Erythritol', quantity: 500, unit: 'g', category: 'Dry goods', icon: '🫙' },
      { name: 'Psyllium Husk', quantity: 200, unit: 'g', category: 'Dry goods', icon: '🫙' },
    ]
  },
  african: {
    name: 'African / West African',
    icon: '🌍',
    description: 'Spices and staples for West African cooking',
    items: [
      { name: 'Long Grain Rice', quantity: 2, unit: 'kg', category: 'Dry goods', icon: '🍚' },
      { name: 'Black Eyed Peas', quantity: 1, unit: 'kg', category: 'Dry goods', icon: '🫘' },
      { name: 'Plantains', quantity: 4, unit: 'pcs', category: 'Produce', icon: '🍌' },
      { name: 'Yam', quantity: 2, unit: 'kg', category: 'Produce', icon: '🥔' },
      { name: 'Palm Oil', quantity: 500, unit: 'ml', category: 'Dry goods', icon: '🫙' },
      { name: 'Groundnut Oil', quantity: 1, unit: 'L', category: 'Dry goods', icon: '🫙' },
      { name: 'Tomato Paste', quantity: 4, unit: 'pcs', category: 'Dry goods', icon: '🥫' },
      { name: 'Scotch Bonnet Peppers', quantity: 6, unit: 'pcs', category: 'Produce', icon: '🌶️' },
      { name: 'Onions', quantity: 2, unit: 'kg', category: 'Produce', icon: '🧅' },
      { name: 'Garlic', quantity: 200, unit: 'g', category: 'Produce', icon: '🧄' },
      { name: 'Ginger', quantity: 200, unit: 'g', category: 'Produce', icon: '🫚' },
      { name: 'Crayfish', quantity: 100, unit: 'g', category: 'Dry goods', icon: '🦐' },
      { name: 'Egusi Seeds', quantity: 200, unit: 'g', category: 'Dry goods', icon: '🫘' },
      { name: 'Bouillon Cubes', quantity: 10, unit: 'pcs', category: 'Dry goods', icon: '🫙' },
      { name: 'Curry Powder', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
      { name: 'Thyme', quantity: 50, unit: 'g', category: 'Spices', icon: '🌿' },
    ]
  },
}

module.exports = PANTRY_TEMPLATES